package cellsociety.Controller;

import cellsociety.Main;

import java.awt.*;
import java.util.*;
import java.util.List;

/**
 * Class for storing the data needed to configure a Simulation
 * Class stores accessible data in myType, myColors, myDataValues, and myGrid
 *
 * Structure based loosely on setup of Game.java in spike_simulation by Robert C. Duvall
 * https://coursework.cs.duke.edu/compsci308_2020spring/spike_simulation/blob/master/src/xml/Game.java
 */
public class Simulation {
    private static ResourceBundle RESOURCES=Main.myResources;

    //name for the type of data file necessary to represent a simulation configuration file
    public static final String DATA_TYPE = RESOURCES.getString("Simulation");

    private static final String MISSING_MESSAGE = RESOURCES.getString("MISSING_MESSAGE");

    //valid fields in the data file for all Simulation objects
    public static final List<String> DATA_FIELDS = List.of(
            RESOURCES.getString("Title"),
            RESOURCES.getString("Rate"),
            RESOURCES.getString("Width"),
            RESOURCES.getString("Height"),
            RESOURCES.getString("GridType")
    );

    private Map<String, Integer> myDataValues;

    //specific data values for this instances
    private SimType myType;
    private String gridType;
    private Map<Point, Integer> myGrid;

    /**
     * Full constructor to initialize a Simulation from given data.
     *
     * @param type the type of Simulation based off of enum SimType
     */
    public Simulation(String type) {
        myType = SimType.of(type);
        myDataValues = new HashMap<>();
        myGrid = new HashMap<>();
    }

    /**
     * Constructor taking in a data structure of Strings.
     *
     * @param dataValues map of field names to their values
     * @param grid map of Points to Integer values generated by XMLParser
     */
    public Simulation(Map<String, String> dataValues, Map<Point, Integer> grid) {
        this(dataValues.get(DATA_FIELDS.get(0)));
        gridType = dataValues.get(RESOURCES.getString("GridType"));
        this.setFields(dataValues);
        myGrid = grid;
    }

    /**
     * Function to set myDataValues to map from a field key to a value
     * Sets value to null if dataValues does not contain the value
     * Note: Implementation of model will need to specify defaults
     *
     * @param dataValues map of field names to their values
     */
    private void setFields(Map<String, String> dataValues) {
        for (int k = 1; k < 5; k ++) {
            String val = dataValues.get(DATA_FIELDS.get(k));
            if (val != null) {
                myDataValues.put(DATA_FIELDS.get(k), Integer.parseInt(val));
            } else  {
                throw new XMLException(MISSING_MESSAGE, myType);
            }
        }
        for (String field: myType.getFields()) {
            if (field.length() > 0) {
                myDataValues.put(field, Integer.parseInt(dataValues.get(field)));
            }
        }
    }

    /**
     * Returns the gridType: all, random, or some
     */
    public String getGridType() {
        return gridType;
    }

    /**
     * Returns simulation type based off of enum SimType
     */
    public SimType getType() {
        return myType;
    }

    /**
     * Returns Map with all String and Integer values for fields
     */
    public Map<String, Integer> getValueSet() {
        return myDataValues;
    }

    /**
     * Returns Integer value matched to field key
     */
    public Integer getValue(String field) {
        return myDataValues.get(field);
    }

    /**
     * Returns Grid, with initialized values (others all default to 0)
     */
    public Map<Point, Integer> getGrid() {
        return myGrid;
    }

}
